swagger: '2.0'
info:
  description: >-
    This is a sample server Bank server.  You can find out more about    
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/).      For this sample, you can use the api
    key `special-key` to test the authorization     filters.
  version: 1.0.0
  title: Swagger
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io
basePath: /v2
tags:
  - name: bank
    description: Everything about your Banks
schemes:
  - http
paths:
  '/bank/{bic}':
    get:
      tags:
        - bank
      summary: Get bank by BIC
      description: ''
      operationId: getBankByBic
      produces:
        - application/xml
        - application/json
      parameters:
        - name: bic
          in: path
          description: 'The bic that needs to be fetched. Use bic1 for testing. '
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Bank'
        '400':
          description: Invalid bic supplied
        '404':
          description: Bank not found
definitions:
  Bank:
    type: object
    properties:
      id:
        type: integer
        format: int64
      bic:
        type: string
      address:
        type: string
    xml:
      name: Bank
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
