swagger: '2.0'
info:
  description: >-
    This is a sample Bank Open API. You can find out more about    
    Swagger at [https://github.com/minsk-hackerspace/api.nbrb.by](https://github.com/minsk-hackerspace/api.nbrb.by)
  version: 0.0.1
  title: Open FinTech API 
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: nbrb.netlify.com
basePath: /fintech
tags:
  - name: account
    description: Everything about your Accounts
schemes:
  - https
paths:
  /accounts:
    get:
      tags:
        - account
      description: Returns all accaunts
      produces:
        - application/json
      responses:
        '200':
          description: A list of accounts.
          schema:
             type: array
             items:
               type: string
  '/accounts/{account}':
    get:
      tags:
        - account
      summary: Get account info
      description: ''
      produces:
        - application/json
      parameters:
        - name: account
          in: path
          description: 'The account info.'
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Balance'
        '400':
          description: Invalid account id
        '404':
          description: Account not Found
  #        schema:
  #          $ref: '#/definitions/ApiResponse'  

#securityDefinitions:
#  petstore_auth:
#    type: oauth2
#    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
#    flow: implicit
#    scopes:
#      'write:pets': modify pets in your account
#      'read:pets': read your pets
#  api_key:
#    type: apiKey
#    name: api_key
#    in: header
definitions:
  Balance:
    type: object
    required:
      - currency
      - amount
    properties:
      currency:
        type: string
        enum:
        - BYN
        - USD
      amount:
        type: number
#  Account:
#    type: object
#    properties:
#      bic:
#        type: string
#      IBAN:
#        type: string
#      balance:
#            $ref: '#/definitions/Balance'
  ApiResponse:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
