openapi: "3.0.0"
info:
  title: "The Open NBRB API"
  description: "The Open API that allows users to obtain existing information of banks"
  version: "1.0.0"
  contact:
    url: openapi.by
    email: info@openapi.by
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/chertby/TheOpenNBRBAPI/1.0.0
#  - url: https://nbrb.openapi.by/{version}
    variables:
     version:
      default: v1
paths:
  /banks:
    get:
      summary: List all banks
      description: The Banks endpoint returns information about the banks. The response includes the display bic, name and other details about each bank.
      operationId: listBanks
      tags:
        - banks
      responses:
        200:
          description: An аrray of banks
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/BankList"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Bank:
      required:
        - bic
        - active
        - name
        - city
        - address
      properties:
        bic:
          type: string
          example: "OLMPBY2X"
        active:
          type: boolean
          example: true
        name:
          type: string
          example: "ОАО Белгазпромбанк"
        city:
          type: string
          example: "Минск"
        address:
          type: string
          description: Address of the bank
          example: "220121, г. Минск, ул. Притыцкого, 60/2"
        phone:
          type: string
          description: Phone of the bank
          example: "120"
    BankList:
      properties:
        banks:
          description: Contains the list of banks
          type: array
          items:
          $ref: "#/components/schemas/Bank"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string